# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Delivery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Delivery
  pod 'SDWebImage', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'TableviewPaginator'

  target 'DeliveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeliveryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
